"""Initial migration.

Revision ID: 62456d39af26
Revises: 
Create Date: 2024-08-27 11:56:40.732538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62456d39af26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
